# Generated by Django 3.0.7 on 2021-04-01 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitBitUser',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('refresh_token', models.TextField()),
                ('scope', models.TextField()),
                ('token_type', models.TextField()),
                ('fitbit_user_id', models.TextField()),
            ],
        ),
    ]
