# Generated by Django 3.0.7 on 2021-04-01 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(blank=True, max_length=50, null=True)),
                ('project_description', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.TextField(choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('groupID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('groupName', models.TextField(max_length=64)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('groupPic', models.ImageField(default='default.png', upload_to='group_pics')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.TextField(choices=[('member', 'member'), ('leader', 'leader')])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.WorkGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField(blank=True, max_length=50, null=True)),
                ('task_description', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.TextField(choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.Project')),
                ('work_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workgroups.WorkGroup')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='work_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.WorkGroup'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.WorkGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=250)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workgroups.WorkGroup')),
            ],
        ),
    ]
